require:
  - rubocop-performance
  - rubocop-rails

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Metrics/BlockLength:
  Exclude:
    - spec/**/*

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - lib/tasks/**/*
    - node_modules/**/*
    - Rakefile
    - Gemfile
    - Gemfile.lock
    - spec/rails_helper.rb
    - spec/spec_helper.rb
