require:
  - rubocop-performance
  - rubocop-rails

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Metrics/BlockLength:
  Exclude:
    - spec/**/*

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - lib/tasks/**/*
    - node_modules/**/*
    - Rakefile
    - Gemfile
    - Gemfile.lock
    - spec/rails_helper.rb
    - spec/spec_helper.rb
