require:
  - rubocop-performance

Rails:
  Enabled: true

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Metrics/BlockLength:
  Exclude:
    - spec/**/*

AllCops:
  TargetRubyVersion: 2.6.1
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - lib/tasks/**/*
    - node_modules/**/*
    - Rakefile
    - Gemfile
    - Gemfile.lock
    - spec/rails_helper.rb
    - spec/spec_helper.rb
