version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
      args:
        - APP_NAME=dogfeeds
    command: bash -c "bin/setup && bin/rails s -b 0.0.0.0 -p 3000"
    tty: true
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/dogfeeds
      - node_modules:/dogfeeds/node_modules
      - vendor:/dogfeeds/vendor
      - log:/dogfeeds/log
      - public:/dogfeeds/public
      - tmp:/dogfeeds/tmp
    environment:
      HOST_NAME: rails
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_HOST: db
volumes:
  node_modules:
    driver: 'local'
  vendor:
    driver: 'local'
  log:
    driver: 'local'
  public:
    driver: 'local'
  tmp:
    driver: 'local'
