version: '3'
services:
  db:
    image: postgres:10.13
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
      args:
        - APP_NAME=dogfeeds
    command: bash -c "bin/rails s -b 0.0.0.0 -p 3000"
    tty: true
    ports:
      - "3000:3000"
    links:
      - db
    tmpfs:
      - /tmp
    volumes:
      - .:/dogfeeds:cached
      - node_modules:/dogfeeds/node_modules
      - bundle:/dogfeeds/vendor/bundle
      - log:/dogfeeds/log
      - packs:/dogfeeds/public/packs
      - packs-test:/dogfeeds/public/packs-test
      - rails-cache:/dogfeeds/tmp/cache
      - git:/dogfeeds/.git
    environment:
      HOST_NAME: rails
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      RUBYOPT: '-w'
      BUNDLE_PATH: /dogfeeds/vendor/bundle
volumes:
  db:
  node_modules:
  bundle:
  log:
  packs:
  packs-test:
  rails-cache:
  git:
