version: '3'
services:
  db:
    image: postgres:10.13
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
  rails: &rails
    image: circleci/ruby:3.0.0-node-browsers
    command: bash -c "bin/rails s -b 0.0.0.0 -p 3000"
    tty: true
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    tmpfs:
      - /tmp
    volumes:
      - .:/dogfeeds:cached
      - node_modules:/dogfeeds/node_modules
      - bundle:/dogfeeds/vendor/bundle
      - log:/dogfeeds/log
      - packs:/dogfeeds/public/packs
      - packs-test:/dogfeeds/public/packs-test
      - rails-cache:/dogfeeds/tmp/cache
      - git:/dogfeeds/.git
    working_dir: /dogfeeds
    user: root
    environment:
      HOST_NAME: rails
      DATABASE_URL: postgres://postgres:password@db:5432
      REDIS_URL: redis://redis:6379/0
      BUNDLE_PATH: /dogfeeds/vendor/bundle
      RAILS_ENV: development
      NODE_ENV: development
  sidekiq:
    <<: *rails
    command: ['bundle', 'exec', 'sidekiq']
    ports: []
volumes:
  db:
  node_modules:
  bundle:
  log:
  packs:
  packs-test:
  rails-cache:
  git:
