version: '3'
services:
  db:
    image: postgres:10.13
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
      args:
        - APP_NAME=dogfeeds
    command: bash -c "bin/setup && bin/rails s -b 0.0.0.0 -p 3000"
    tty: true
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/dogfeeds:cached
      - node_modules:/dogfeeds/node_modules
      - bundle:/dogfeeds/vendor/bundle
      - /dogfeeds/log
      - /dogfeeds/public/packs
      - /dogfeeds/public/packs-test
      - /dogfeeds/public/assets
      - /dogfeeds/tmp
      - /dogfeeds/.git
    environment:
      HOST_NAME: rails
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      RUBYOPT: '-w'
      BUNDLE_PATH: /dogfeeds/vendor/bundle
volumes:
  node_modules:
    driver: 'local'
  bundle:
    driver: 'local'
