version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.0.0

web-default-enviroments: &web-default-enviroments
  RAILS_ENV: test
  NODE_ENV: test
  PGHOST: 127.0.0.1
  DATABASE_USER: circleci
  DATABASE_PASSWORD: password
  BASIC_AUTH_USER: 'root'
  BASIC_AUTH_PASSWORD: 'password'

web: &web
  - image: circleci/ruby:3.0.2-node-browsers
    environment:
      <<: *web-default-enviroments

db: &db
  - image: circleci/postgres:10.13
    environment:
      POSTGRES_USER: circleci
      POSTGRES_PASSWORD: password

executors:
  web:
    docker:
      - <<: *web
  web-db:
    docker:
      - <<: *web
      - <<: *db

commands:
  attach_current:
    steps:
      - attach_workspace:
          at: .
  install_node_deps:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ./node_modules
          with-cache: true
  install_ruby_deps:
    steps:
      - ruby/install-deps:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          path: ./vendor/bundle
          with-cache: true
  rails_migration:
    steps:
      - run:
          name: run migration
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
  build_webpack:
    steps:
      - run:
          name: build webpack
          command: yarn build:test
  store_atifacts:
    parameters:
      path:
        type: string
    steps:
      - store_artifacts:
          path: << parameters.path >>
jobs:
  build:
    executor:
      name: web
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  node_build:
    executor:
      name: web
    steps:
      - attach_current
      - install_node_deps
  ruby_build:
    executor:
      name: web
    steps:
      - attach_current
      - install_ruby_deps
  ruby_lint:
    executor:
      name: web
    steps:
      - attach_current
      - install_ruby_deps
      - run:
          name: run rubocop
          command: bundle exec rubocop
      - run:
          name: run brakeman
          command: bundle exec brakeman
      - run:
          name: run rubycritic
          command: bundle exec rubycritic
      - store_atifacts:
          path: tmp/rubycritic
  ruby_test:
    executor:
      name: web-db
    steps:
      - attach_current
      - install_ruby_deps
      - install_node_deps
      - rails_migration
      - build_webpack
      - run:
          name: run tests
          command: bundle exec rspec spec/
      - store_atifacts:
          path: coverage
workflows:
  version: 2
  build:
    jobs:
      - build
      - ruby_build:
          requires:
            - build
      - ruby_lint:
          requires:
            - ruby_build
      - ruby_test:
          requires:
            - ruby_build
            - node_build
      - node_build:
          requires:
            - build
