default: &default
  adapter: postgresql
  encoding: unicode

database_config: &database_config
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

development:
  primary:
    <<: *database_config
    database: dogfeeds_development
  replica:
    <<: *database_config
    database: dogfeeds_development
    replica: true

test:
  primary:
    <<: *database_config
    database: dogfeeds_test
  replica:
    <<: *database_config
    database: dogfeeds_test
    replica: true

production:
  primary:
    <<: *database_config
    database: dogfeeds_production
  replica:
    <<: *database_config
    database: dogfeeds_production
    replica: true
