production:
  basic_auth:
    user: <%= ENV['BASIC_AUTH_USER'] %>
    password: <%= ENV['BASIC_AUTH_PASSWORD'] %>
development:
  basic_auth:
    user: <%= ENV['BASIC_AUTH_USER'] %>
    password: <%= ENV['BASIC_AUTH_PASSWORD'] %>
test:
  basic_auth:
    user: <%= ENV['BASIC_AUTH_USER'] %>
    password: <%= ENV['BASIC_AUTH_PASSWORD'] %>
