default: &default
  manifest_path: public/packs/manifest.json

development:
  <<: *default
  cache_manifest: false

test:
  <<: *default
  cache_manifest: false
  manifest_path: public/packs-test/manifest.json

production:
  <<: *default
  cache_manifest: true
